###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

networks:
  default:
    driver: bridge

services:

  mysql:
    image: mysql
    container_name: binance-mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=88888888
      - MYSQL_DATABASE=binance
      - MYSQL_USER=msarapii
      - MYSQL_PASSWORD=88888888
    ports:
      - "8091:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: msarapii
      PMA_PASSWORD: 88888888
    ports:
      - "8090:80"
    restart: always
    depends_on:
      - mysql
    networks:
      - default

  webserver:
    image: nginx:alpine
    container_name: binance-trade-webserver
    working_dir: /application
    networks:
      - default
    volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8089:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: binance-trade-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

